import sys, os
'''

This is the post_analysis_diagnosis.py file.


'''



def make_forcing_list():
    
    # make the forcing list
    # find the FORCINGS folder
    scenario_path = os.getcwd()
    cwd = os.getcwd()
    cwd = cwd.split('/')
    for i in range(len(cwd)):
        if os.path.isdir('/'.join(cwd[:-i])+'/FORCINGS') == True:
            forcings_path = '/'.join(cwd[:-i])+'/FORCINGS'
            break
    forcinglist = os.listdir(forcings_path)
    forcinglist = [f for f in forcinglist if f.startswith('data_')]
    # sort the forcing list
    forcinglist.sort()
    print (len(forcinglist), 'forcing files found in the FORCINGS folder.')

    # make the list of forcing files
    f = open(forcings_path+'/forcing_list.txt', 'w')
    for forcing in forcinglist:
        f.write('../FORCINGS/'+forcing+' ')
        cord = forcing.split('_')[1:]
        f.write(cord[0]+' '+cord[1]+'\n')
    f.close()

    return forcings_path



def run_VICstats(forcings_path):

    # forcing list file name
    forcinglist = f'{forcings_path}/forcing_list.txt'
    # send the command to run VICstats
    os.system(f'VicOutputASMStats {forcinglist} TRUE test 0.0625 ./diagnosis/col_list.txt 01012000 09302015 A FALSE TRUE')

    '''
    Usage: VicOutputASMStats <file list file> <Output ArcGrid: TRUE/FALSE> <output prefix> <grid resolution> <column list file> <start date> <end date> <V|A|S|M|W|D> <OVERWRITE: TRUE/FALSE> <PrtAllPeriods: TRUE/FALSE>

        This program produces either an ARC/INFO ASCII grid file
        (output ArcGrid = TRUE) or an XYZ file (Output ArcGrid = FALSE) of the average
        of the selected data column for the given time period.

        The following additional variables can be calculated by this
        program, and used with the standard list of summary metrics, the
        required columns are in the VIC files being processed.
        Add the variable names below to your statistics control file
        to include them in the analysis:
        - OUT_PE Penman potential evaporation, requires "OUT_R_NET",
          "OUT_GRND_FLUX", "OUT_WIND", "OUT_SURF_TEMP", "OUT_REL_HUMID",
          "OUT_AIR_TEMP",
        - OUT_TOTAL_RUNOFF is the sum of "OUT_RUNOFF" and "OUT_BASEFLOW",
        - OUT_TOTAL_SOIL_MOIST is the sum of "OUT_SOIL_MOIST" for each layer,
        - OUT_MGDD modified growing degree day (from mrcc.isws.illinois.edu),
          requires "IN_TMIN" and "IN_TMAX",
        - OUT_PLANT_DAY is a Boolean variable indicating whether or not soil
          surface conditions support planting, requires "OUT_SOIL_MOIST_0"
          and "OUT_SOIL_TEMP_0".  Also requires that a file with top soil
          layer field capacity [mm] be provided following the statistic
          definition in the soil control file.
        - OUT_MRCC_CHILL_HR is the number of chilling hours (fruit trees)
          based on MRCC methodology, requires "IN_TMIN" and "IN_TMAX".
        - OUT_UTAH_CHILL_HR is the number of chilling hours (fruit trees)
          based on UTAH methodology, requires "IN_TMIN" and "IN_TMAX".
        - OUT_DMWD is the number of working days defined by DRAINMOD,
          requires "OUT_PREC" and "OUT_SOIL_MOIST_0".  Also requires that
          a file with top soil layer saturation [mm] be provided following
          the statistic definition in the soil control file.
        - OUT_DSFW is the number of of days suitable for field work
          (Gramig et al, 2017), requires "IN_PREC", "IN_TMIN", "IN_TMAX",
          and "Soil Drainge Class".
        <file list> is a file containing the full grid file name and location,
                latitude and longitude of the grid cell, for each grid cell to be
                included.
        <output prefix> is the prefix (path and start of file name) for the
                output files that will be generated by this program.  A suffix
                will be added to all file names to separate individual output
                for each variable, and for each tperiod (year, season, month,
                etc). Files containing multi-year average statistics for annual,
                seasonal and monthly periods will use "9999" for
                the date in the file name.
        <grid resolution> is the resolution in degrees of the desired output
                grid.
        <column list file> is a multi-column ASCII file that lists the column
                name for each column to be output.  Followed by the statistic
                to be computed and a thresehold if required by the statistic.

                Statistic options include:
                - Mean value                            'mean',
                - Cumulative value                      'sum',
                - Standard Deviation                    'stdev',
                - Maximum value                         'max',
                - Day of maximum value                  'max_day',
                - Minimum value                         'min',
                - Day of minimum value                  'min_day',
                - First value                           'first',
                - Last value                            'last',
                - Last day over thres.                  'ldayo' <thres>,
                - Last day under thres.                 'ldayu' <thres>,
                - First day over thres.                 'fdayo' <thres>,
                - First day under thres.                'fdayu' <thres>,
                - Days over threshold                   'othres' <thres>,
                - Days under threshold                  'uthres' <thres>,
                - Average days over threshold           'avgdaysothres' <thres>,
                - Average days under threshold          'avgdaysuthres' <thres>,
                - Average value over threshold          'avgvalothres' <thres>,
                - Average value under threshold         'avgvaluthres' <thres>,
                - Sum value over threshold              'sumvalothres' <thres>,
                - Sum value (deficit) under threshold   'sumvaluthres' <thres>,
                - Consecutive days over threshold       'daysothres' <thres>,
                - Consecutive days under threshold      'daysuthres' <thres>,
                - Last day over thres before middle     'ldaymido' <thres>,
                - Last day under thres before middle    'ldaymidu' <thres>,
                - First day over thres after middle     'fdaymido' <thres>,
                - First day under thres after middle    'fdaymidu' <thres>,
                - Number of times threshold is crossed  'crossthres' <thres>,
                - RB Index (flashiness)                 'RBI',
                - TQ mean (days spent above mean)       'Tqmean',
                - Seven day low value                   '7daylow',
                - Quantile value                        'quan' <quantile>.

                NOTE: Any single value threshold can be replaced with
                "FILE <shortname> <filename>" to provide spatially
                distributed thresholds.  <shortname> is used to replace the
                threshold value in the output filename, and <filename> must
                be the same format (Arc Grid/XYZ) being used
                for overall processing.
        <start date> and <end date> are the starting and ending dates of the
                period of interest in MMDDYYYY format (MM = month, DD = day,
                YYYY = year - date must be 8 characters).
        <V|A|S|M|W|D> export Annual a(V)erage, (A)nnual, (S)easonal, (M)onthly,
                (W)eekly, (D)aily or annual repeating (P)eriod grids for all
                years in the file
                - Annual uses given start date to start year;
                - Seasonal uses Winter = DJF, Spring = MAM, Summer = JJA, and
                  Autumn = SON;
                - Weekly parses data into 7 day weeks starting with the given
                  start date.
                - Period requires a range in MM-DD_MM-DD format or key phrase
                  "grow" for dynamic growing season, for example
                  "P08-15_11-01" to define the fall working window of
                  August 15th to November 1st.
        <OVERWRITE> if set to TRUE then the output grid files will be
                overwritten.  The default is to replace values in existing
                files with new data.
        <PrtAllPeriods> if set to TRUE then the program will write all output
                files (all years, all seasons, etc), if set to FALSE only
                annual averages will be written.

    '''


















forcings_path = make_forcing_list()
run_VICstats(forcings_path)